name: Deploy on Tag Push

on:
  push:
    tags:
      - '*'  # triggers on any tag

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/   # adjust if your build output folder is different

  deploy:
    name: Deploy to Server
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: /tmp/build   # temp location on the self-hosted runner

      - name: Deploy to server
        run: |
          set -e

          BASE_PATH="/var/www/apps/httpdocs"
          LIVE_DIR="$BASE_PATH/SFI-UI"
          DATE=$(date +%F)
          COUNT=1

          # Find unique backup folder name
          while [ -d "$BASE_PATH/SFI-UI-$DATE-$COUNT" ]; do
            COUNT=$((COUNT + 1))
          done
          BACKUP_DIR="$BASE_PATH/SFI-UI-$DATE-$COUNT"

          echo "Backing up existing SFI-UI to: $BACKUP_DIR"
          mv "$LIVE_DIR" "$BACKUP_DIR"

          echo "Deploying new build"
          cp -r /tmp/build "$LIVE_DIR"

          echo "Restarting Apache"
          sudo systemctl restart apache2
