name: Deploy Static Site to EC2 (Apache)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload and Deploy to Apache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Project Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./**/*"  # Recursively include all files and folders
          target: "/home/ubuntu/2129_crispy_kitchen_build"

      - name: Deploy to Apache Web Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Backup current site (optional)
            sudo mv /var/www/html /var/www/html_backup_$(date +%s) || true

            # Deploy new files
            sudo rm -rf /var/www/html
            sudo mkdir -p /var/www/html
            sudo cp -r /home/ubuntu/2129_crispy_kitchen_build/* /var/www/html/

            # Set permissions
            sudo chown -R www-data:www-data /var/www/html

            # Restart Apache
            sudo systemctl restart apache2
