name: Deploy to EC2 on Tag Push

on:
  push:
    tags:
      - '*'  # Runs on all new tags

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2 via SSH
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          REPO_PAT: ${{ secrets.REPO_PAT }}
          TAG: ${{ github.ref_name }}
        run: |
          echo '
          set -e

          BASE_PATH="/var/www/admin/httpdocs"
          LIVE_DIR="$BASE_PATH/SFI-Admin-UI"
          DATE=$(date +%F)
          COUNT=1

          while [ -d "$BASE_PATH/SFI-Admin-UI-$DATE-$COUNT" ]; do
            COUNT=$((COUNT + 1))
          done

          BACKUP_DIR="$BASE_PATH/SFI-Admin-UI-$DATE-$COUNT"
          echo "Backing up $LIVE_DIR to $BACKUP_DIR"
          if [ -d "$LIVE_DIR" ]; then
            sudo mv "$LIVE_DIR" "$BACKUP_DIR"
          fi

          echo "Creating fresh $LIVE_DIR directory"
          sudo mkdir -p "$LIVE_DIR"

          echo "Downloading release ZIP for t
