name: Deploy to EC2 on Tag Push

on:
  push:
    tags:
      - '*'  # Runs on all new tags

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2 via SSH
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          REPO_PAT: ${{ secrets.REPO_PAT }}
          TAG: ${{ github.ref_name }}
          REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: ${{ github.repository_owner }}
        run: |
          echo '
          set -e

          BASE_PATH="/var/www/admin/httpdocs"
          LIVE_DIR="$BASE_PATH/SFI-Admin-UI"
          DATE=$(date +%F)
          COUNT=1

          while [ -d "$BASE_PATH/SFI-Admin-UI-$DATE-$COUNT" ]; do
            COUNT=$((COUNT + 1))
          done

          BACKUP_DIR="$BASE_PATH/SFI-Admin-UI-$DATE-$COUNT"
          echo "Backing up $LIVE_DIR to $BACKUP_DIR"
          if [ -d "$LIVE_DIR" ]; then
            sudo mv "$LIVE_DIR" "$BACKUP_DIR"
          fi

          echo "Creating fresh $LIVE_DIR directory"
          sudo mkdir -p "$LIVE_DIR"

          echo "Downloading release ZIP for tag: $TAG"

          WORK_DIR="/home/ubuntu/deploy-$TAG"
          ZIP_PATH="$WORK_DIR/release.zip"

          rm -rf "$WORK_DIR"
          mkdir -p "$WORK_DIR"

          curl -L -H "Authorization: token $REPO_PAT" \
            -o "$ZIP_PATH" \
            "https://github.com/$ORG_NAME/$REPO_NAME/archive/refs/tags/$TAG.zip"

          unzip "$ZIP_PATH" -d "$WORK_DIR"
          EXTRACTED_FOLDER=$(find "$WORK_DIR" -maxdepth 1 -type d -name "$REPO_NAME-*")

          echo "Deploying to $LIVE_DIR"
          sudo rsync -av "$EXTRACTED_FOLDER"/ "$LIVE_DIR"/

          echo "Cleaning up..."
          rm -rf "$WORK_DIR"

          echo "Restarting Apache..."
          sudo systemctl restart apache2

          echo "Deployment complete for tag $TAG"
          ' | ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST \
              'REPO_PAT='"$REPO_PAT"' TAG='"$TAG"' REPO_NAME='"$REPO_NAME"' ORG_NAME='"$ORG_NAME"' bash -s'
