name: Deploy SFI-UI

on:
  workflow_dispatch:
    inputs:
      release_zip:
        description: "Path or URL to release.zip file"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          BASE_PATH="/var/www/apps/httpdocs"
          LIVE_DIR="$BASE_PATH/SFI-UI"
          DATE=$(date +%F)
          COUNT=1

          # Find unique backup folder name
          while [ -d "$BASE_PATH/SFI-UI-$DATE-$COUNT" ]; do
            COUNT=$((COUNT + 1))
          done
          BACKUP_DIR="$BASE_PATH/SFI-UI-$DATE-$COUNT"

          echo "BASE_PATH=$BASE_PATH" >> $GITHUB_ENV
          echo "LIVE_DIR=$LIVE_DIR" >> $GITHUB_ENV
          echo "BACKUP_DIR=$BACKUP_DIR" >> $GITHUB_ENV

      - name: Backup existing live folder
        run: |
          echo "Backing up existing SFI-UI to: $BACKUP_DIR"
          sudo mv "$LIVE_DIR" "$BACKUP_DIR" || echo "No existing deployment found"

      - name: Download release zip
        run: |
          TEMP_DIR="/tmp/SFI-UI-deploy"
          rm -rf "$TEMP_DIR"
          mkdir -p "$TEMP_DIR"
          curl -L "${{ github.event.inputs.release_zip }}" -o "$TEMP_DIR/release.zip"
          unzip "$TEMP_DIR/release.zip" -d "$TEMP_DIR"

      - name: Deploy to live directory
        run: |
          sudo cp -r /tmp/SFI-UI-deploy/* "$LIVE_DIR"

      - name: Restart Apache
        run: |
          sudo systemctl restart apache2
